### PR TITLE
fixed confgen and readout for raw recording TP's

### PR DESCRIPTION
**Pull request by ShyamB97**
- app_confgen.py was updated to test raw recording of raw_tp data.
 - minor changes to FakeCardReader
 - DefaultRequestHandlerModel used in place of EmptyFragementRequestHandlerModel for  RAW_WIB_TRIGGERPRIMITIVE_STRUCT in CreateReadout.hpp

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
I tried compiling these changes, in conjunction with the changes on the philiprodrigues/trigger-object-overlay branch in detdataformats, but I got a compiler error about `No such file or directory: #include "detdataformats/wib/RawWIBTp.hpp"`.

Are there changes in detdataformats that need to accompany the changes in this PR?
Thanks,
Kurt

**Comment by ShyamB97** [comment]
Hi Kurt,
Yes there should be an upcoming PR for detdataformats which will accompany this PR, so it is probably worth waiting for those changes before compiling.
Cheers,
Shyam

**Review by roland-sipos — CHANGES_REQUESTED** [review]
LGTM

**Review by roland-sipos — APPROVED** [review]
LGTM

**Comment by roland-sipos** [comment]
Waiting for `detdataformats` push privileges to add RawWIBTp. Then I merge this in.

**Pull request merged**
